# Site Settings
title: Studio Code
email: iambriitneysam@gmail.com
description: Blog para programacion
baseurl: "/jekflix-template" # the subpath of your site, e.g. /blog
url: 
google_analytics: 

# User Settings
username: Briitney
user_description: estudiante.
disqus_username: 

# Social Media
# Remove the item if you don't need it
github_username: yosoybriitneysam
facebook_username: yosoybriitneysam
twitter_username: 
instagram_username: 
linkedin_username: 
medium_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
